COQDEVDIR := /home/shyuan/.opam/4.11.1/lib/coq//user-contrib/dx
CPRINTERDIR := 
COMPCERTSRCDIR := /home/shyuan/.opam/4.11.1/.opam-switch/build/coq-compcert.3.9
INSTALLCOMPCERTCPRINTER := true
DXDIR := /home/shyuan/GitLab/dx
