DXDIR := /home/shyuan/.opam/4.11.1/lib/coq/user-contrib/dx
COMPCERTDIR := /home/shyuan/.opam/4.11.1/lib/coq-variant/compcert32/compcert
CLIGHTGEN32DIR := /home/shyuan/.opam/4.11.1/variants/compcert32/bin
COMPCERTSRCDIR := /home/shyuan/.opam/4.11.1/.opam-switch/build/coq-compcert-32.3.9
