#include "verifier.h"
#include <stdint.h> /* for uintptr_t */

static __attribute__((always_inline)) inline unsigned int eval_ins_len(struct verifier_state* st)
{
  return (*st).ins_len;
}

static __attribute__((always_inline)) inline unsigned long long eval_ins(struct verifier_state* st, unsigned int idx)
{
  return *((*st).ins + idx);
}

/*******************below code are automatically generated by dx (after repatch) ***************************/
