OPAMPREFIX := /home/cav/.opam/bpf
DXDIR := $(OPAMPREFIX)/lib/coq/user-contrib/dx
CLIGHTGEN32DIR := $(OPAMPREFIX)/variants/compcert32/bin
COMPCERTSRCDIR := $(OPAMPREFIX)/.opam-switch/build/coq-compcert-32.3.9
